services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: package-track-auth
    depends_on:
      - redis
    ports:
      - "8081:8081"
    env_file:
      - .env
